- package.json
Hi! This is just a small change that makes it easier to import worker-dom in a project using Rollup — the rollup-plugin-node-resolve plugin first looks for the `"module"` field in package.json, and only then falls back to `"main"`.
It also removes the extension from `"main"`, per the current Node recommendation, so that all bases are covered.
Thanks for this extraordinary project!
> add pkg.module and make pkg.main extension-agnostic

- README.md
When looking through the `Usage` section of the README I thought that there might be some room to clarify it slightly. 
* Preface that there are two variants at the beginning
* Clarify the example uses a direct script tag approach, and make using it as such more apparent by using a explanatory path 
* Separate the code for module / global variants
> Clarify usage instructions in the README

- demo/index.html
This PR stratifies out the demos into sub categories making it easier for developers to find what they are looking for.
> Add subheadings to demo page to stratify out different demo types

- demo/index.html
- demo/server.mjs
- package.json
Polka `0.5.0` had a minor API change that made the demo fallover.
This PR moves the demo to the newer API.
> Update Polka to 0.5.0

- config/rollup.main-thread.js
- config/rollup.worker-thread.js
- package.json
Addresses #110.
Chose the format `unminified.${filename}.${extension}` so the default would still use the minification passes that are custom to the closure compiler version in the library.
> Add unminified builds

- demo/server.js
- package.json
When using the ESM loader, CJS options are disabled. This means `__dirname` is not available and we were previously relying on `PWD` from `process.env`.
Unfortunately, this doesn't work on Windows. (#119)
So, while the contents of this file is a `module`, we need to keep the `js` extension until the minimum version of node supported is 10. Node 10 is the first version to support [`url.fileURLToPath(url)`](https://nodejs.org/api/url.html#url_url_fileurltopath_url) and [`import.meta`](https://github.com/tc39/proposal-import-meta).
Once Node 10 is the default, we can move back to `mjs`, and use `import.meta` instead of the CJS value `__dirname`.
> Restore Windows Demo Compatibility

- demo/server.js
Looks like the recent fix for Windows broke the paths for the demo pages.
Let's fix em up.
> Correct Paths for Demos

- demo/comments/comments.js
- demo/index.html
- package.json
- src/test/comment/textContent.ts
- src/test/element/innerHTML.ts
- src/test/mutationobserver/replaceChild.ts
- src/worker-thread/dom/Comment.ts
- src/worker-thread/dom/Document.ts
- src/worker-thread/dom/Element.ts
- src/worker-thread/dom/Node.ts
Several popular frameworks use `Comment` nodes to reserve spots in DOM for future mutations.
This PR is WIP adding support for Comment nodes.
> Add Support for Comment Nodes

- src/worker-thread/dom/Document.ts
- src/worker-thread/initialize.ts
Browsers have uppercased tag names, so this resulted in all hydrated elements being created as `HTMLElement`. Also realized we need a test for for `Document`. :)
> Fix casing bug with NODE_NAME_MAPPING

- demo/preact-dbmon/index.html
- package.json
- src/worker-thread/dom/Element.ts
Two issues, additional markup remained in DBMon and `Element.querySelector` wasn't using the normalized localName.
> Repair Demos

- src/worker-thread/dom/Node.ts
Node.appendChild should return the element that was appended, according to the docs at MDN. https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild
This is a crucial fix to use d3's select element creation `d3.select().append('svg')...`, and to support d3 within WorkerDOM.
> Return the input node at Node.appendChild.

- config/rollup.main-thread.js
- config/rollup.worker-thread.js
- package.json
By using both, we gain the logic that Closure Compiler knows (and Terser doesn't) and the mangling changes that Terser can apply that CC doesn't know yet.
Net result... .1KB saved on `worker.mjs`!
> New version of Closure Compiler + Terser

- config/rollup.plugins.js
- src/worker-thread/dom/Document.ts
`transformChunk` lifecycle for `Plugin` is deprecated, and has been replaced with the `renderChunk` lifecycle.
Additionally, re-added the `documentForTesting` since it's used in the debugger demo page.
> Update Rollup build plugin for Rollup 1.0 Release

- src/main-thread/callbacks.ts
- src/main-thread/index.safe.ts
- src/main-thread/index.ts
- src/main-thread/install.ts
- src/main-thread/worker.ts
This allows AMP to perform the fetch of worker/author scripts which:
1. Avoids need for a fetch polyfill.
2. Allows AMP to set its typical request headers and query params.
3. Enforce a size constraint on the author script.
/to @kristoferbaxter
> Allow delegating of script fetching to caller

- src/main-thread/serialize.ts
- src/main-thread/worker.ts
The current module-level `initialStrings` and `strings` are never freed. This reworks the code so they're stack allocated objects, and will be cleaned up after creating the worker.
> Free initial strings after worker creation

- src/main-thread/strings.ts
- src/test/htmlelement/serialize.ts
- src/test/mutationobserver/addEventListener.ts
- src/test/mutationobserver/removeEventListener.ts
- src/worker-thread/strings.ts
Arrays are a much more efficient backing store for this use case: http://jsbench.github.io/#7c89704a2ed38b0746c8d52431de7bb6
> Use an array backing for strings

- src/main-thread/callbacks.ts
- src/main-thread/index.safe.ts
- src/main-thread/install.ts
Allows callers to apply pre-hydration UX (e.g. partial opacity) to signal non-interactivity to users.
> Add hydration callback

- demo/index.html
- demo/two-roots/index.html
- demo/two-roots/two-roots.js
- package.json
- src/main-thread/DOMPurifySanitizer.ts
- src/main-thread/commands/bounding-client-rect.ts
- src/main-thread/commands/event-subscription.ts
- src/main-thread/debugging.ts
- src/main-thread/index.safe.ts
- src/main-thread/install.ts
- src/main-thread/mutator.ts
- src/main-thread/nodes.ts
- src/main-thread/strings.ts
- src/main-thread/worker.ts
Fixes: #297
Most of the main-thread code is now scoped per `baseElement` or `NodeContext`.
The one issue I haven't yet resolved - is treatment of `DebuggingContext` which currently bundled into main `install.ts` and adds about 0.6-0.7Kb.
/to @kristoferbaxter @choumx
> Support multiple worker-dom roots in the main thread

- src/test/node/replaceChild.ts
- src/worker-thread/dom/Node.ts
Fixes a couple tests in #319. Would've been a nightmare for a publisher using Preact/React to find.
> Node.replaceChild() must set parentNode of newChild

- src/worker-thread/WorkerDOMGlobalScope.ts
- src/worker-thread/index.safe.ts
- src/worker-thread/index.ts
- Add `WorkerGlobalScope.navigator` to `WorkerDOMGlobalScope`.
- This will come as a `WorkerNavigator`, a subset of the `Navigator` interface.
@jridgewell @choumx
> Add Navigator

- package.json
- src/test/element/outerHTML.ts
- src/worker-thread/dom/Element.ts
Partial for #319. Fixes bugs like this:
```ts
const input = document.createElement('input');
// Expected: '<input>'
// Actual: '<input></input>'
console.log(input.outerHTML);
```
> Node.outerHTML: Don't output end tags for void elements 

- src/test/cssstyledeclaration/setCssText.ts
- src/worker-thread/css/CSSStyleDeclaration.ts
Partial for #319.
Older versions (> ~2 weeks ago) of Preact supports objects when rendering `style` in JSX, which results in setting `cssText` to a non-string:
https://github.com/developit/preact/blob/3aaa578270c0c6cd1fb7f5cf992737eec2934433/src/dom/index.js#L81-L83
Looks like they've made a bunch of changes since. Time to pull and try everything again. 😫
> Support non-string edge case for set cssText

- src/test/mutationobserver/replaceChild.ts
- src/test/node/replaceChild.ts
- src/worker-thread/dom/Node.ts
Partial for #319.
Importantly, fixes this bug:
```js
parent.appendChild(one);
parent.appendChild(two);
parent.replaceChild(two, one);
// Expected: [one]
// Actual: [one, one]
log(parent.childNodes); 
```
Also fixes one case of [HierarchyRequestError](https://dom.spec.whatwg.org/#concept-node-replace) where newChild is an ancestor of parent.
> Fix Node.replaceChild when newChild is already a child

- src/worker-thread/dom/Element.ts
- src/worker-thread/dom/Node.ts
Fixes #326. Also fixes bunch of tests for #319 due to Preact browser tests' use of `babel-register`.
#328 fixes the same issue for worker-dom's ES5 output, but not for projects that import the ES6 output and have their own transpilation pipeline (e.g. amphtml). Plus, the spec-compliant Babel transpile is pretty large.
> Avoid super.getter

- src/test/element/innerHTML.ts
- src/third_party/html-parser/html-parser.ts
- src/worker-thread/dom/Element.ts
- Instead of using `new Element()` inside of `html-parser`, use `document.createElement()`
- Instead of using `new Text()` inside of `html-parser`, use `document.createTextNode()`
- Instead of using `new Comment()` inside of `html-parser`, use `document.createComment()`
- Fixes #350 
@jridgewell @choumx 
cc/ @caroqliu
> Have innerHTML use document.createElement().

- src/test/element/innerHTML.ts
- src/third_party/html-parser/html-parser.ts
- When parsing html, change the element wrapping the content from a `<div>` to a `<q>`, which will not close any other tag automatically.
- Fixes #372 
- Fix test that failed after changing this behavior (was wrongly phrased in the first place).
@choumx @jridgewell 
cc/ @fstanis
> Change the html-parser's wrapping element.

- src/test/htmloptionelement/value.ts
- src/test/htmlselectelement/options.ts
- src/test/htmlselectelement/value.ts
- src/transfer/TransferrableKeys.ts
- src/worker-thread/dom/HTMLOptionElement.ts
- src/worker-thread/dom/HTMLSelectElement.ts
- src/worker-thread/dom/Node.ts
`HTMLSelectElement.set value` wasn't implemented, and is needed for a demo I am working on.
This PR changes `Node` to allow for a new method that runs after insertion or removal, but before the microtask collection in `MutationObserver`. This lets extensions of `Node` like `HTMLSelectElement` update local information on each insertion/removal.
> Enable value setter for HTMLSelectElement

- package.json
- src/transfer/TransferrableKeys.ts
- src/worker-thread/MutationObserver.ts
- src/worker-thread/MutationTransfer.ts
- src/worker-thread/SyncValuePropagation.ts
- src/worker-thread/dom/Document.ts
- src/worker-thread/dom/Element.ts
- src/worker-thread/dom/HTMLInputElement.ts
- src/worker-thread/dom/HTMLOptionElement.ts
- src/worker-thread/dom/Node.ts
- src/worker-thread/long-task.ts
Ordering of updates for events is crucial, and allows us to avoid the mutate/transfer cycle.
Since we've separated out `MutationObserver` from `MutationTransfer`, we can now safely apply sync value updates without triggering unintentional changes to attributes.
> Ivar sync updates

- src/main-thread/configuration.ts
- src/main-thread/install.ts
- src/main-thread/worker.ts
- src/worker-thread/MutationTransfer.ts
- src/worker-thread/dom/Document.ts
There were two regressions with `0.4.0`. #410 
1. onHydrate from `WorkerDOMConfiguration` never fired. This was intentional, since the method no longer served its original purpose. It's been removed in this PR.
2. `phase` was not sent with mutations between threads. This has been fixed, and types have been tightened to prevent future regressions.
Please note: This will be released as `0.5.0`.
> Correct regression with 0.4.0

- config/rollup.main-thread.js
- config/rollup.plugins.js
Worker source template literal contained newlines and extraneous spaces.
This is not an attempt to use a minifier on its source, but rather a small number of safe reductions in character count.
> Remove Whitespace from Worker Template Literal 

- package.json
- src/main-thread/tsconfig.json
- src/test/main-thread/tsconfig.json
- src/test/tsconfig.json
- src/transfer/tsconfig.json
- src/worker-thread/tsconfig.json
This draft show the change to ensure when creating a release we don't accidentally use the test format of the TypeScript output.
Do you think this change could be made in #473?
> Incremental TypeScript

- package.json
- src/worker-thread/css/CSSStyleDeclaration.ts
- src/worker-thread/dom/DOMTokenList.ts
- src/worker-thread/dom/Element.ts
- src/worker-thread/dom/HTMLAnchorElement.ts
- src/worker-thread/dom/HTMLIFrameElement.ts
- src/worker-thread/dom/HTMLLinkElement.ts
- src/worker-thread/dom/HTMLOptionElement.ts
- src/worker-thread/dom/HTMLTableCellElement.ts
This should avoid allocating a `propertyBackedAttributes` object map for every element instance. Instead, the class defines how its property-backed attributes behaves.
> Define property-backed attributes on the class constructor

- src/test/domtokenlist/add.test.ts
- src/test/domtokenlist/contains.test.ts
- src/test/domtokenlist/item.test.ts
- src/test/domtokenlist/remove.test.ts
- src/test/domtokenlist/replace.test.ts
- src/test/domtokenlist/toggle.test.ts
- src/test/domtokenlist/value.test.ts
- src/worker-thread/dom/DOMTokenList.ts
- src/worker-thread/dom/Element.ts
- src/worker-thread/dom/HTMLAnchorElement.ts
- src/worker-thread/dom/HTMLIFrameElement.ts
- src/worker-thread/dom/HTMLLinkElement.ts
- src/worker-thread/dom/HTMLTableCellElement.ts
Not every element is going to need its `DOMTokenList`s, so we shouldn't be initializing every one of them when the element itself is created.
This is part two of updating how `DOMTokenList` is synchronized across the threads. This optimization is work looking at independent of the final product, even if we don't choose to land the final sync work.
[Compare](https://github.com/jridgewell/worker-dom/compare/lazy-init-DOMTokenList...lazy-init-DOMTokenList-2) against https://github.com/ampproject/worker-dom/pull/471, since this PR includes #471's commits.
> Lazy initialize DOMTokenList

- package.json
- src/test/DocumentCreation.ts
- src/test/main-thread/offscreen-canvas.test.ts
- src/test/svgelement/cloneNode.test.ts
- src/test/svgelement/namespaceURI.test.ts
- src/worker-thread/WorkerDOMGlobalScope.ts
- src/worker-thread/dom/Element.ts
- src/worker-thread/index.amp.ts
- src/worker-thread/index.ts
This fixes cloneNode to support Elements with custom namespaces.
> Clone SVG and other Elements with custom namespaces

- package.json
- src/test/cssstyledeclaration/appendKeys.test.ts
- src/transfer/TransferrableKeys.ts
This test ensures we don't break `CSSStyleDeclaration` again with numerical keys from `TransferrableKeys`.
> CSSStyleDeclaration Test for numerical keys

- config/rollup.worker-thread.js
With debugging/console disabled, transpiled to ES5, and compiled/tersed.
> Add "amp/worker/worker.js" output

- src/main-thread/commands/attribute.ts
- src/main-thread/commands/bounding-client-rect.ts
- src/main-thread/commands/character-data.ts
- src/main-thread/commands/child-list.ts
- src/main-thread/commands/event-subscription.ts
- src/main-thread/commands/image-bitmap.ts
- src/main-thread/commands/interface.ts
- src/main-thread/commands/long-task.ts
- src/main-thread/commands/object-creation.ts
- src/main-thread/commands/object-mutation.ts
- src/main-thread/commands/offscreen-canvas.ts
- src/main-thread/commands/property.ts
- src/main-thread/mutator.ts
- src/test/main-thread/long-task.test.ts
- src/test/main-thread/object-creation.test.ts
- src/test/main-thread/object-mutation.test.ts
Small refactor that moves the retrieval of "target" element inside each mutation processor. 
This is desirable since we have new processors that don't require a target element (e.g. localStorage).
/to @kristoferbaxter
> Move getNode(<target>) inside mutation processors

- package.json
- src/main-thread/commands/interface.ts
- src/main-thread/commands/long-task.ts
- src/main-thread/deserializeTransferrableObject.ts
- src/main-thread/install.ts
- src/main-thread/mutator.ts
- src/main-thread/nodes.ts
- src/main-thread/strings.ts
- src/test/DocumentCreation.ts
- src/test/main-thread/deserializeTransferrableObject.test.ts
- src/test/main-thread/long-task.test.ts
- src/test/main-thread/mutator.test.ts
- src/test/main-thread/object-creation.test.ts
- src/test/main-thread/object-mutation.test.ts
- src/worker-thread/MutationObserver.ts
- src/worker-thread/WorkerDOMGlobalScope.ts
- src/worker-thread/canvas/OffscreenCanvasPolyfill.ts
- src/worker-thread/index.amp.ts
- src/worker-thread/index.ts
Also rename `Strings` to `StringContext` to be consistent with other "Context" classes, and other minor clean up items.
/to @kristoferbaxter
> Allowlist indexedDB, Strings->StringContext, other cleanup

- package.json
- src/main-thread/worker.ts
- src/worker-thread/WorkerDOMGlobalScope.ts
- src/worker-thread/canvas/CanvasRenderingContext2D.ts
- src/worker-thread/canvas/OffscreenCanvasPolyfill.ts
- src/worker-thread/dom/Node.ts
- src/worker-thread/index.ts
I suspect #578 broke native OffscreenCanvas but the examples tested fine manually because of the polyfill case. More digging to do here.
First, going to fix the `ownerDocument: Node` type issue which results in `ownerDocument.defaultView.foo` being typed as `any` due to [the escape hatch](https://github.com/ampproject/worker-dom/pull/578#discussion_r303655032) in `Node`.
> Upgrade TS to 3.5.3 and fix some bugs

- package.json
- src/worker-thread/index.amp.ts
WebSockets were not on the Allowlist for the AMP version of the WorkerThread.
> WebSocket Support for AMP

- config/rollup.main-thread.js
- config/rollup.worker-thread.js
- package.json
- src/main-thread/main-thread.d.ts
- src/main-thread/mutator.ts
- src/main-thread/worker.ts
- src/test/main-thread/helpers/env.ts
Each distributed thread's code for `amp-script` integration includes additional logging information.
~~This PR removes the logging since it can impact performance.~~
This PR uses the similar to AMP logic for retaining logs (presence of `development` or `log` in `location.hash`.
Edit: Changed approach based on PR feedback.
> Suppress Console Messages in AMP output

- package.json
- src/main-thread/worker.ts
- src/test/htmlelement/globalEventProperties.test.ts
- src/transfer/TransferrableKeys.ts
- src/worker-thread/dom/HTMLElement.ts
- src/worker-thread/initialize.ts
Implement Global Event Handlers, frequently used by Frameworks to determine which events need special lower-casing of event names.
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers
Implemented directly on `HTMLElement` since this appears to be the detection logic for Preact.
> Global event handlers

- .travis.yml
Refactor Travis Test configuration to split work for `size` test versus unit tests.
This means the size will only be determined from the linux environment and reduces the complexity of testing on OS X.
> Travis refactor: Jobs

- src/worker-thread/index.amp.ts
Remove `Blob` from allowlist in the AMP output.
> Remove Blob from Allowlisted Globals

- package.json
- src/main-thread/commands/attribute.ts
- src/main-thread/commands/bounding-client-rect.ts
- src/main-thread/commands/character-data.ts
- src/main-thread/commands/child-list.ts
- src/main-thread/commands/event-subscription.ts
- src/main-thread/commands/image-bitmap.ts
- src/main-thread/commands/interface.ts
- src/main-thread/commands/long-task.ts
- src/main-thread/commands/object-creation.ts
- src/main-thread/commands/object-mutation.ts
- src/main-thread/commands/offscreen-canvas.ts
- src/main-thread/commands/property.ts
- src/main-thread/commands/storage.ts
- src/main-thread/mutator.ts
- src/test/main-thread/long-task.test.ts
- src/test/main-thread/object-creation.test.ts
- src/test/main-thread/object-mutation.test.ts
- src/test/main-thread/string-properties.test.ts
- src/transfer/TransferrableMutation.ts
Enables enforcement user gesture constraints in use cases like `amp-script`.
Context: https://github.com/ampproject/amphtml/issues/26375
> Allow filtering mutation executions on user-visibility

- src/test/domtokenlist/toggle.test.ts
- src/worker-thread/dom/DOMTokenList.ts
Throws a `TypeError` with the message 'DOMException' and addresses #750.
> DOMTokenList.toggle cannot accept whitespace entities

- src/test/domtokenlist/toggle.test.ts
- src/worker-thread/dom/DOMTokenList.ts
fixes #831
[old spec discussion](https://github.com/whatwg/dom/issues/64)
relevant bits being gecko had a discrepancy (that is fixed in modern firefox), and IE ignores `force` all together, so this is never be good there either way
> Do not strictly check force values in DOMTokenList.toggle

- config/rollup.plugins.js
- package.json
Using loose mode results in output that does not execute as expected.
> Do not use loose mode for ES5 transpilation

- src/test/element/innerHTML.test.ts
- src/third_party/html-parser/README.md
- src/third_party/html-parser/html-parser.ts
Addressed the easy half of https://github.com/ampproject/worker-dom/issues/613
cc @caroqliu.
Note that we can get a really big bang for the innerHTML buck if we also decide to decode just the 4 required bits for [html encoding](https://developer.mozilla.org/en-US/docs/Glossary/Entity) (`<` `>`, `&`, `"`). Could be worth doing in addition to all numeric.
> decode numeric html entitites

- package.json
- src/test/element/innerHTML.test.ts
- src/third_party/html-parser/README.md
- src/third_party/html-parser/html-parser.ts
Followup to https://github.com/ampproject/worker-dom/pull/947. I think it may make sense to decode these 4 in particular, given their prominence in html encoding. See https://developer.mozilla.org/en-US/docs/Glossary/Entity
> Decode HTML Reserved Characters (>,<,&,").

- demo/preact-map/renovate.json
- demo/react-map/renovate.json
- renovate.json
**Summary**
There are numerous steps we can take for [noise reduction](https://docs.renovatebot.com/noise-reduction/) of Renovate. This PR enables one of the basic ones, _automerging_. 
Potential future change: `automergeType=branch`, which would enable the bot to auto-push to master without creating a PR first in case of a branch with passing tests. It would only create a PR (and therefore notification) in case of failures.
> Configure renovate-bot to automerge PRs that have passing tests.

- src/main-thread/commands/long-task.ts
- src/test/main-thread/long-task.test.ts
**problem**
Consumers of `worker-dom` using the `longTask` API are notified of a new long task via callback and are notified of a long task end via Promise. In general this is fine.
There are situation in which both of these events occur within the same task. This is particularly true when the page is inactive and therefore `postMessage` processing is delayed until the page has been returned to.
A naive consumer will then run into the strange situation where they are notified of a 2nd long task start before receiving the 1st end. For `<amp-script>` this meant a sequence of events like this:
1. Long task start
2. Long task start
3. Long task end  (now `inLongTask=false`)
4. `<amp-script>` mutation pump receives mutations but inLongTask=false and activation time was set by (3), and …
> Fix race between long task start and end handlers.

- demo/preact-map/renovate.json
- demo/react-map/renovate.json
- renovate.json
**summary**
Makes two changes to the renovate config, both intended to reduce noise.
1. Group all package upgrades together.
2. Schedule the PR to be created once per week, instead of at all hours.
Note: there is a separate request I filed to install `renovate-approve-bot` for auto-approving PRs. They'll still be blocked by passing tests. All of these changes combined should significantly reduce our maintenance burden.
> renovate-bot: only once a week, and all package

- demo/iframe/iframe.html
- demo/iframe/index.html
- demo/iframe/storage.js
- demo/index.html
- package.json
- src/main-thread/worker.ts
- src/test/main-thread/initialize-storage.test.ts
- src/worker-thread/initialize.ts
**summary**
Fixes https://github.com/ampproject/amphtml/issues/30691. Makes it so that worker-dom no longer blows up when storage access is denied by the browser.  From the worker's perspective, localStorage and sessionStorage end up as null.
> storage should throw if unsupported

- .github/workflows/size.yml
- .github/workflows/test.yml
Necessary for compatibility with @kristoferbaxter/bytes.
@kristoferbaxter: do you know how the blocking CI is set up? Why is it waiting for 12.x to complete & return success given that I'm modifying to 14.x here.
EDIT: I believe there is a repo setting I don't have access to that must be flipped
> Update workflows to use Node 14.x.

- src/main-thread/commands/storage.ts
- src/main-thread/debugging.ts
- src/test/main-thread/commands/storage.test.ts
- src/test/mutation-transfer/amp.test.ts
- src/worker-thread/amp/amp.ts
**summary**
Fixes two bugs discovered in https://github.com/ampproject/amphtml/issues/32984. Note that both fixes are only **5 LOC**. The rest are tests. 
1. When `AMP.getState()` is called with no args, the key was recorded as undefined in worker-thread but empty string in main-thread. The fix was to coerce falsy keys to an empty string in worker-thread as well. Without this the messages would never be matched properly and worker-thread always resolved the request with `null`.
2. When the `storageKey` being requested is the 0th indexed string in StringContext, the StorageProcessor would always send over null. Essentially never a problem for a dom post-hydration, but could easily happen via `nodom`.
As a bonus change, I've also added 'GET_STORAGE' to the list of debuggable events.
> storage fixes

- config/rollup.main-thread.js
- demo/index.html
- demo/sandboxed/index.html
- demo/sandboxed/sandbox-iframe.html
- package.json
- src/main-thread/configuration.ts
- src/main-thread/exported-worker.ts
- src/main-thread/iframe-worker.ts
- src/main-thread/index.amp.ts
- src/main-thread/main-thread.d.ts
- src/main-thread/worker.ts
- src/test/main-thread/iframe-worker.test.ts
**background**
The primary use-case of `worker-dom` is to power [`<amp-script>`](https://amp.dev/documentation/components/amp-script/).  With the current mechanisms in place, it acts well for 1p (mostly trusted) scripts. `amp-script` now has a new [use case](https://github.com/ampproject/amphtml/issues/30193) to allow less-trusted 3p scripts to run on the page without a CSP, and for this we need a stronger security boundary.
The goal of this PR is to enable a "sandboxed" mode by creating the Worker within a sandboxed iframe instead of within the main frame.
**design**
When starting up, `worker-dom` will create an iframe instead of a WebWorker. This iframe needs to perform a handshaking process and then essentially act as a proxy between the subframe Worker and the main frame. To make …
> Introduce sandboxed iframe mode.

- config/rollup.worker-thread.js
- src/worker-thread/server-lib.ts
**summary**
Creates a new binary for server-side usage.  
**Sample API Usage**
```js
import {createDocument} from 'worker-dom/server-lib'
const doc = createDocument();
const body = doc.createElement('body');
doc.appendChild(body);
console.log(doc.body.outerHTML) --> <body></body>
```
Note: this is super experimental and is very likely to change over the coming months
> create new server-build, for server side use cases

- src/test/main-thread/initialize-storage.test.ts
- src/worker-thread/hydrate.d.ts
- src/worker-thread/hydrate.ts
- src/worker-thread/index.amp.ts
- src/worker-thread/index.nodom.amp.ts
- src/worker-thread/index.ts
- src/worker-thread/initialize-storage.ts
- src/worker-thread/initialize.ts
**summary**
The `nodom` binary historically hasn't called `hydrate` since there is no DOM to hydrate. What I didn't realize at the time was the `LocalStorage` and `SessionStorage` are also initialized during hydration.
- This PR adds in storage support for nodom binaries.
- It also extracts storage init to its own file to avoid dragging along all of `Document` (which in turn pulls in the vdom)
> nodom: support storage

- src/worker-thread/MutationTransfer.ts
- src/worker-thread/Storage.ts
- src/worker-thread/WorkerDOMGlobalScope.ts
- src/worker-thread/amp/amp.ts
- src/worker-thread/dom/DocumentStub.ts
- src/worker-thread/function.ts
- src/worker-thread/index.nodom.amp.ts
- src/worker-thread/initialize-storage.ts
**summary**
Fixes https://github.com/ampproject/amphtml/issues/35902
1. Renames `DocumentLite.ts` to `DocumentStub.ts`. The filename should match the exported class :)
2. Modifies `workerDOM` export to actually be the `document.defaultView` which is essential for propagating properties (localStorage/sessionStorate) to the global `self`. This is also how the regular binary works. See below snippets
https://github.com/ampproject/worker-dom/blob/11ff429516e4dcfb4f64794bed5f52163d5d9166/src/main-thread/worker.ts#L80
https://github.com/ampproject/worker-dom/blob/11ff429516e4dcfb4f64794bed5f52163d5d9166/src/worker-thread/index.amp.ts#L137
**testing done**
Copied the built binaries over to a local `amphtml` and confirmed that localStorage access was available on `self`
> nodom: workerDOM should be document.defaultView

- src/worker-thread/dom/DOMTokenList.ts
**summary**
It is generally useful to be compatible with Babel's loose mode. This means avoiding funky behavior in the ECMAScript spec.
A violation in worker-dom was the spreading of Sets. Technically this works in JS:
```js
assertEqual([...new Set([1,2])].join(','), '1,2');
```
But in a loose mode, spreads are assumed to only occur on Array and the results may surprise you:
```js
// Loose mode:
assertEqual([...new Set([1,2])].join(','), '[object Set]');
```
> babel loose mode compat: dont spread Set

- package.json
- src/test/node/nextSibling.test.ts
- src/test/node/previousSibling.test.ts
- src/worker-thread/dom/CharacterData.ts
- src/worker-thread/dom/DOMTokenList.ts
- src/worker-thread/dom/Element.ts
- src/worker-thread/dom/elementSibling.ts
- web_compat_table.md
Use case: amp-carousel's buildDom
> Add support for nextElementSibling and previousElementSibling

- src/test/mutation-transfer/amp.test.ts
- src/worker-thread/amp/amp.ts
https://github.com/ampproject/worker-dom/commit/a6bcd6f515de985c6dc48e013e57757eb6b8d962 changed the indice by adding 1 to all SET/GET operation. However, amp.js is not updated.
Fixes https://github.com/ampproject/amphtml/issues/39016 (will need to release worker-dom and update depencency on amphtml though)
Uncertain on what is the best way to cover this scenario by test, but could be a further work.
It appears that this change will only affect amp.
> Fix off-by-1 index bug in amp state

- src/test/htmlelement/globalEventProperties.test.ts
- src/worker-thread/dom/HTMLElement.ts
Removing of event listener with in a way like: `element.onclick = null;`, stores `null` as a handler.
> Unsubscription/removing "on" listener must not cause an error

- config/rollup.plugins.mjs
- package.json
rollup plugin has updated and uses `start` and `en` instead of `range` now.
> Fix rollup plugin extension

- src/worker-thread/function.ts
This is causing some error reporting on amphtml. It should be a json but wasn't. Changing this would cause amphtml to emit an error message in console only.
> Fix error message format to be a valid message
