- demo/index.html
- demo/prime-numbers/index.html
- demo/prime-numbers/primes.js
I wrote a small demo that generating primes (attempt at demoing a longer running task) and appending them to the DOM. It's for a blog post I'm writing which is a brief introduction to WorkerDOM. If you don't feel it's valuable, feel free to close it.
> A demo of long running tasks

- src/main-thread/DOMPurifySanitizer.ts
- src/main-thread/hydrator.ts
- src/main-thread/index.safe.ts
- src/main-thread/main-thread.d.ts
- src/main-thread/mutator.ts
- src/main-thread/nodes.ts
> Support configurable hooks for DOMPurifySanitizer

- src/main-thread/index.safe.ts
- src/main-thread/index.ts
- src/main-thread/install.ts
https://github.com/ampproject/amphtml/pull/18665/files#r224279646
Open to better names than `upgrade()`. :)
> API to specify author URL separate from base element

- src/test/htmlelement/querySelector.ts
- src/worker-thread/dom/Element.ts
> Adds support for ID, Class & Tag selectors to Element.querySelector

- src/test/htmlelement/querySelectorAll.ts
- src/worker-thread/dom/Element.ts
> Adds support for ID, Class & Tag selectors to Element.querySelectorAll

- demo/hello-world/index.html
- src/main-thread/worker.ts
> Hydrating line breaks

- src/main-thread/mutator.ts
- src/test/htmlbuttonelement/autofocus.ts
- src/test/htmlelement/reflectProperties.ts
- src/test/htmlelement/translate.ts
- src/test/reflectPropertiesHelper.ts
- src/worker-thread/dom/HTMLElement.ts
- src/worker-thread/dom/HTMLInputElement.ts
- src/worker-thread/dom/enhanceElement.ts
> Support for boolean and enumerated attributes

- package.json
- src/test/comment/cloneNode.ts
- src/test/element/cloneNode.ts
- src/test/text/cloneNode.ts
- src/worker-thread/dom/Comment.ts
- src/worker-thread/dom/Element.ts
- src/worker-thread/dom/Node.ts
- src/worker-thread/dom/Text.ts
Adds support for `Node.cloneNode`.
> Node.cloneNode

- package.json
- src/test/node/appendChild.ts
> Test for Node.appendChild returning newly appended child

- package.json
Preparing for the code changes introduced in #178.
> Package Size Bump for DocumentFragments

- package.json
Reverts ampproject/worker-dom#229
See: https://github.com/ampproject/worker-dom/pull/229#issuecomment-455694053
> Revert "Update dependency dompurify to v1.0.9"

- src/main-thread/worker.ts
- src/test/cssstyledeclaration/appendKeys.ts
- src/worker-thread/css/CSSStyleDeclaration.ts
> Filter invalid styles from CSSStyleDeclaration

- src/main-thread/worker.ts
- src/worker-thread/WorkerDOMGlobalScope.ts
- src/worker-thread/index.safe.ts
- src/worker-thread/index.ts
* Add navigator with the userAgent property to worker-dom.
* Fixes #285 
@jridgewell @choumx
> Implement Navigator.userAgent property.

- src/main-thread/commands/bounding-client-rect.ts
- src/main-thread/commands/event-subscription.ts
- src/main-thread/debugging.ts
- src/main-thread/mutator.ts
- src/main-thread/nodes.ts
* Change the return type of `src/main-thread/nodes.ts#getNode()` to be nullable.
* In places where this method is called, expect a nullable return value.
* Fixes #280
🐛
@choumx @jridgewell
> 🐛Change the return type of `getNode` to be nullable.

- src/main-thread/worker.ts
- src/worker-thread/WorkerDOMGlobalScope.ts
- src/worker-thread/index.safe.ts
- src/worker-thread/index.ts
Reverts ampproject/worker-dom#288
Re: https://github.com/ampproject/worker-dom/issues/285#issuecomment-464184492
> Revert "Implement Navigator.userAgent property."

- README.md
- web_compat_table.md
Adds the current compatibility status for DOM APIs and frameworks
> Create web_compat.md with compatibility details

- src/test/element/attribute.ts
- src/worker-thread/dom/Element.ts
Partial for #317. Fixes 6 test failures in #319.
> Convert attribute values to strings

- README.md
Made it [relative](https://help.github.com/en/articles/basic-writing-and-formatting-syntax#relative-links) too.
> README: Fixed link to compat table

- src/test/node/textContent.ts
- src/worker-thread/dom/Element.ts
Needed to slice the array before modifying its contents.
Fix for #371.
> Fix for #371, remove a slice of the childNodes

- package.json
- src/main-thread/configuration.ts
- src/main-thread/index.ts
- src/main-thread/worker.ts
- src/test/Emitter.ts
- src/transfer/TransferrableKeys.ts
- src/worker-thread/MutationTransfer.ts
- src/worker-thread/dom/Document.ts
- src/worker-thread/initialize.ts
- src/worker-thread/nodes.ts
Re-introduce the `Hydration` phase.
> AMPScript Contract

- web_compat_table.md
just remove some duplicate lines
> clean up dupes from compat table

- package.json
- src/main-thread/commands/attribute.ts
- src/main-thread/commands/bounding-client-rect.ts
- src/main-thread/commands/character-data.ts
- src/main-thread/commands/child-list.ts
- src/main-thread/commands/event-subscription.ts
- src/main-thread/commands/interface.ts
- src/main-thread/commands/long-task.ts
- src/main-thread/commands/offscreen-canvas.ts
- src/main-thread/commands/offscreen-polyfill-calls.ts
- src/main-thread/commands/property.ts
- src/main-thread/configuration.ts
- src/main-thread/install.ts
- src/main-thread/mutator.ts
- src/test/DocumentCreation.ts
- src/test/main-thread/long-task.test.ts
- src/test/main-thread/mutator.test.ts
- src/test/main-thread/offscreen-canvas.test.ts
- src/test/svgelement/cloneNode.test.ts
- src/test/svgelement/namespaceURI.test.ts
- src/transfer/TransferrableMutation.ts
- src/worker-thread/WorkerDOMGlobalScope.ts
- src/worker-thread/dom/Element.ts
- src/worker-thread/index.amp.ts
- src/worker-thread/index.ts
> Allowlist support for mutators

- package.json
- src/main-thread/worker.ts
- src/test/DocumentCreation.ts
- src/worker-thread/WorkerDOMGlobalScope.ts
- src/worker-thread/index.amp.ts
- src/worker-thread/index.ts
Addresses last remaining issue for Aurelia.
> HTMLElement in global scope

- package.json
- src/worker-thread/css/CSSStyleDeclaration.ts
Tests will be created in a separate commit.
> Fix for CSSStyleDeclaration Regression

- src/main-thread/commands/attribute.ts
- src/test/element/attribute.test.ts
Fixes #562. Good old truthy footgun.
/to @kristoferbaxter
> Fix empty attribute value being processed as removals

- package.json
Just released: https://github.com/ampproject/worker-dom/releases/tag/v0.15.0
> Update package.json version to 0.15.0

- web_compat_table.md
> localStorage and sessionStorage are now supported

- demo/default-input-listener/author.js
- demo/default-input-listener/index.html
- demo/index.html
- src/main-thread/commands/child-list.ts
- src/main-thread/commands/event-subscription.ts
- src/main-thread/debugging.ts
- src/main-thread/serialize.ts
- src/main-thread/worker.ts
Resolves #628.
Tests are forthcoming.
> Default input listener value propagation

- src/test/element/getElementsByName.test.ts
- src/worker-thread/dom/Element.ts
- web_compat_table.md
Implements `Element.getElementsByName`, resolving #783.
> Implement Element.getElementsByName

- web_compat_table.md
https://github.com/ampproject/amphtml/issues/22253#issuecomment-623544446
> Event.preventDefault() is not supported

- src/worker-thread/index.amp.ts
- src/worker-thread/worker-thread.d.ts
Resolves https://github.com/ampproject/amphtml/issues/28714
> Log less in AMP output

- package.json
makes it slightly easier to toss this in temporarily to rollup configs.
> dev deps: add rollup-plugin-analyzer

- demo/hello-world/hello-world.js
- package.json
- src/test/DocumentCreation.ts
- src/test/worker-thread/AnimationFrame.test.ts
- src/worker-thread/AnimationFrame.ts
- src/worker-thread/WorkerDOMGlobalScope.ts
- src/worker-thread/index.amp.ts
- src/worker-thread/index.ts
Some browsers do not ship this API to worker threads.
> Polyfill Request and Cancel Animation Frame for Worker Thread

- package.json
@kristoferbaxter: do you remember what broke in the mainline of `np`, so I can check if its been fixed?
> update to latest version of np

- package.json
Bump version to match latest release
> bump to v0.26.0

- demo/sandboxed/index.js
**summary**
Followup to https://github.com/ampproject/worker-dom/pull/1047, I had forgotten to `git add` a demo file. It is referenced by [demos/sandboxed/index.html](https://github.com/ampproject/worker-dom/pull/1047/files#diff-f0d7580ef643f1e6fb4a61394886ac190818f49437a40c02ab4973a1b24528eeR10)
> Add sandboxed.js demo file

- src/test/htmlelement/querySelectorAll.test.ts
- src/worker-thread/dom/Node.ts
Followup fix to a lil bug in https://github.com/ampproject/worker-dom/pull/1096.
Note: the bug only affects server-lib.
---
Followup: need to come up with a good system for parameterizing tests
> server-lib bugfix: need scopingRoot

- .gitignore
- package.json
upgrading a few dependencies to be able to publish latest code
> Upgrade dependencies
